package se.dosf.communitybase.beans;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.enums.GroupAccessLevel;
import se.unlogic.hierarchy.core.beans.Group;
import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.i18n.Language;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLUtils;

@Table(name="users")
@XMLElement
public class CommunityUser extends User implements Elementable {

	private static final long serialVersionUID = 5571711627678650626L;

	@Key
	@DAOManaged(autoGenerated=true)
	@XMLElement
	private Integer userID;
	
	@DAOManaged
	@XMLElement
	private String email;

	@DAOManaged
	@WebPopulate(required=true,maxLength=60)
	@XMLElement
	private String firstname;

	@DAOManaged
	@WebPopulate(required=true,maxLength=80)
	@XMLElement
	private String lastname;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private String phoneHome;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private String phoneMobile;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private String phoneWork;

	@DAOManaged
	@XMLElement
	private Timestamp lastLogin;
	
	@DAOManaged
	@XMLElement
	private Timestamp currentLogin;

	@DAOManaged
	@WebPopulate(required=true,minLength=6,maxLength=50)
	private String password;

	@DAOManaged
	@XMLElement
	private Timestamp lastResume;
	
	@DAOManaged
	@XMLElement
	private Integer resume;

	@DAOManaged
	@XMLElement
	private boolean enabled;

	@DAOManaged
	@XMLElement
	private boolean admin;

	@DAOManaged
	@XMLElement
	private Timestamp added;

	private Map<CommunityGroup, GroupRelation> groups;
	
	@SuppressWarnings("unused")
	@DAOManaged
	@ManyToMany(linkTable="groupusers")
	@XMLElement
	private ArrayList<CommunityGroup> communityGroups;
	
	@XMLElement
	private List<School> schools;

	@DAOManaged
	@XMLElement
	private Language language;

	public CommunityUser() {}

	public String getUserName() {
		return this.email;
	}

	public List<School> getSchools() {
		return schools;
	}

	public void setSchools(List<School> schools) {
		this.schools = schools;
	}

	
	
/*	@Override
	public List<? extends Group> getGroups() {

		if (this.groups != null) {
			return new ArrayList<CommunityGroup>(groups.keySet());
		}

		return null;
	}
*/
	public Map<CommunityGroup, GroupRelation> getGroupMap(){
		return this.groups;
	}

	@Override
	public Collection<Group> getGroups() {
		
		List<Group> groups = null;
		
		if (this.groups != null) {			
			
			groups = new ArrayList<Group>(); 
			
			for(CommunityGroup group : this.groups.keySet()) {
				
				groups.add(group);
				
			}
			
			return groups;
		}

		return groups;
	}
	
	public Collection<CommunityGroup> getCommunityGroups() {
		
		if (this.groups != null) {
			
			return new ArrayList<CommunityGroup>(groups.keySet());
			
		}
		
		return null;
	}

	public void removeGroup(CommunityGroup group) {

		if (this.groups != null) {
			this.groups.remove(group);
		}
	}

	public GroupAccessLevel getAccessLevel(CommunityGroup group) {

		GroupRelation groupRelation = this.getGroupRelation(group);

		if (groupRelation != null) {
			return groupRelation.getAccessLevel();
		}

		return null;
	}

	public String getComment(CommunityGroup group) {

		GroupRelation groupRelation = this.getGroupRelation(group);

		if (groupRelation != null) {
			return groupRelation.getComment();
		}

		return null;
	}

	public GroupRelation getGroupRelation(CommunityGroup group) {

		if (this.groups != null) {
			return groups.get(group);
		}

		return null;
	}

	public void setGroups(Map<CommunityGroup, GroupRelation> groups) {
		this.groups = groups;
	}

	public void addGroup(CommunityGroup communityGroup, GroupRelation groupRelation) {

		if (this.groups == null) {
			this.groups = new HashMap<CommunityGroup, GroupRelation>();
		}

		this.groups.put(communityGroup, groupRelation);
	}

	public Integer getResume() {
		return resume;
	}

	public void setResume(Integer resume) {
		this.resume = resume;
	}

	public void setAdded(Timestamp added) {
		this.added = added;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setFirstname(String firstName) {
		this.firstname = firstName;
	}

	public void setLastname(String lastName) {
		this.lastname = lastName;
	}

	public void setLastLogin(Timestamp lastLogin) {
		this.lastLogin = lastLogin;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Override
	public Timestamp getAdded() {
		return added;
	}

	@Override
	public String getEmail() {
		return email;
	}

	@Override
	public String getFirstname() {
		return firstname;
	}

	@Override
	public Timestamp getLastLogin() {
		return lastLogin;
	}

	@Override
	public String getLastname() {
		return lastname;
	}

	@Override
	public String getPassword() {
		return password;
	}

	@Override
	public Integer getUserID() {
		return userID;
	}

	@Override
	public String getUsername() {
		return email;
	}

	@Override
	public boolean isAdmin() {
		return admin;
	}

	@Override
	public boolean isEnabled() {
		return enabled;
	}

	public String getPhoneHome() {
		return phoneHome;
	}

	public void setPhoneHome(String phoneHome) {
		this.phoneHome = phoneHome;
	}

	public String getPhoneMobile() {
		return phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	public String getPhoneWork() {
		return phoneWork;
	}

	public void setPhoneWork(String phoneWork) {
		this.phoneWork = phoneWork;
	}

	public Timestamp getLastResume() {
		return lastResume;
	}

	public void setLastResume(Timestamp lastResume) {
		this.lastResume = lastResume;
	}

	@Override
	public String toString() {
		return this.getFirstname() + " " + this.getLastname() + " (ID: " + this.getUserID() + ")";
	}

	@Override
	public List<Element> getAdditionalXML(Document doc) {

		// Insert the root element node
		Element communityUserAttributesElement = doc.createElement("communityUserAttributes");

		// Add lastlogin
		if (this.getPhoneHome() != null) {
			communityUserAttributesElement.appendChild(XMLUtils.createCDATAElement("phoneHome", this.getPhoneHome().toString(), doc));
		}

		if (this.getPhoneMobile() != null) {
			communityUserAttributesElement.appendChild(XMLUtils.createCDATAElement("phoneMobile", this.getPhoneMobile().toString(), doc));
		}

		if (this.getPhoneWork() != null) {
			communityUserAttributesElement.appendChild(XMLUtils.createCDATAElement("phoneWork", this.getPhoneWork().toString(), doc));
		}

		if (this.getLastResume() != null) {
			communityUserAttributesElement.appendChild(XMLUtils.createElement("lastResume", this.getLastResume().toString(), doc));
		}

		if(this.getResume() != null) {
			communityUserAttributesElement.appendChild(XMLUtils.createCDATAElement("resume", this.getResume().toString(), doc));
		}

		if (groups != null && !this.groups.isEmpty()) {

			Element groupsElement = doc.createElement("groups");

			communityUserAttributesElement.appendChild(groupsElement);

			for (Entry<CommunityGroup, GroupRelation> entry : this.groups.entrySet()) {

				Element groupElement = entry.getKey().toXML(doc);

				groupElement.appendChild(entry.getValue().toXML(doc));

				groupsElement.appendChild(groupElement);
			}
		}

		if(schools != null && !this.schools.isEmpty()){

			Element schoolsElement = doc.createElement("schools");
			communityUserAttributesElement.appendChild(schoolsElement);

			for(School school : schools){
				schoolsElement.appendChild(school.toXML(doc));
			}
		}

		return Collections.singletonList(communityUserAttributesElement);
	}


	@Override
	public Timestamp getCurrentLogin() {
		return currentLogin;
	}


	public void setCurrentLogin(Timestamp currentLogin) {
		this.currentLogin = currentLogin;
	}

	@Override
	public Language getLanguage() {
		return language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Override
	public String getPreferedDesign() {

		return null;
	}
}
