package se.dosf.communitybase.modules.weekmenu.beans;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;

@Table(name = "weekmenu_template_menus")
@XMLElement
public class WeekMenu implements Elementable {
	
	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer weekMenuID;

	@DAOManaged(columnName = "weekMenuTemplateID")
	@ManyToOne
	@XMLElement
	private WeekMenuTemplate weekMenuTemplate;

	@DAOManaged
	@XMLElement
	private Integer week;
	
	@DAOManaged(columnName = "monday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String monday;

	@DAOManaged(columnName = "tuesday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String tuesday;

	@DAOManaged(columnName = "wednesday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String wednesday;

	@DAOManaged(columnName = "thursday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String thursday;

	@DAOManaged(columnName = "friday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String friday;

	@DAOManaged(columnName = "saturday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String saturday;

	@DAOManaged(columnName = "sunday")
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String sunday;

	public WeekMenuTemplate getWeekMenuTemplate() {

		return weekMenuTemplate;
	}

	public void setWeekMenuTemplate(WeekMenuTemplate weekMenuTemplate) {

		this.weekMenuTemplate = weekMenuTemplate;
	}

	public Integer getWeek() {

		return week;
	}

	public void setWeek(Integer day) {

		this.week = day;
	}

	public String getMonday() {

		return monday;
	}

	public void setMonday(String title) {

		this.monday = title;
	}

	public String getTuesday() {

		return tuesday;
	}

	public void setTuesday(String tuesdayTitle) {

		this.tuesday = tuesdayTitle;
	}

	public String getWednesday() {

		return wednesday;
	}

	public void setWednesday(String wednesdayTitle) {

		this.wednesday = wednesdayTitle;
	}

	public String getThursday() {

		return thursday;
	}

	public void setThursday(String thursdayTitle) {

		this.thursday = thursdayTitle;
	}

	public String getFriday() {

		return friday;
	}

	public void setFriday(String fridayTitle) {

		this.friday = fridayTitle;
	}

	public String getSaturday() {

		return saturday;
	}

	public void setSaturday(String saturdayTitle) {

		this.saturday = saturdayTitle;
	}

	public String getSunday() {

		return sunday;
	}

	public void setSunday(String sundayTitle) {

		this.sunday = sundayTitle;
	}
	
	public boolean isEmpty() {

		return monday == null && tuesday == null && wednesday == null && friday == null && saturday == null && wednesday == null;
	}

	@Override
	public String toString() {

		return "WeekMenuTemplate: " + this.weekMenuTemplate + " V." + this.week;
	}

	@Override
	public Element toXML(Document doc) {

		return XMLGenerator.toXML(this, doc);
	}

}
