package se.dosf.communitybase.modules.weekmenu.beans;

import java.sql.Timestamp;
import java.util.List;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.unlogic.hierarchy.core.beans.User;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;

@Table(name = "weekmenu_templates")
@XMLElement
public class WeekMenuTemplate implements Elementable {

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer weekMenuTemplateID;

	@DAOManaged
	@WebPopulate(maxLength = 255, required = true)
	@XMLElement
	private String name;

	@DAOManaged(columnName = "posterID")
	@XMLElement(childName = "poster")
	private User poster;

	@DAOManaged
	@XMLElement
	private Timestamp lastEdit;

	@DAOManaged
	@WebPopulate(required = true)
	@XMLElement
	private Integer weeks;

	@DAOManaged
	@WebPopulate(required = true)
	@XMLElement
	private Integer startWeek;

	@DAOManaged
	@WebPopulate(required = true)
	@XMLElement
	private Integer startYear;

	@DAOManaged
	@WebPopulate(required = true)
	@XMLElement
	private Integer endWeek;

	@DAOManaged
	@WebPopulate(required = true)
	@XMLElement
	private Integer endYear;

	@DAOManaged
	@OneToMany(autoGet = true, autoAdd = true, autoUpdate = true)
	@XMLElement
	private List<WeekMenu> menus;

	public Integer getWeekMenuTemplateID() {

		return weekMenuTemplateID;
	}

	public void setWeekMenuTemplateID(Integer newsletterID) {

		this.weekMenuTemplateID = newsletterID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public void setPoster(User poster) {

		this.poster = poster;
	}

	public User getPoster() {

		return poster;
	}

	public void setLastEdit(Timestamp date) {

		this.lastEdit = date;
	}

	public Timestamp getLastEdit() {

		return this.lastEdit;
	}

	public Integer getWeeks() {

		return weeks;
	}

	public void setWeeks(Integer weeks) {

		this.weeks = weeks;
	}

	public Integer getStartWeek() {

		return startWeek;
	}

	public void setStartWeek(Integer startWeek) {

		this.startWeek = startWeek;
	}

	public List<WeekMenu> getMenus() {

		return menus;
	}

	public void setMenus(List<WeekMenu> menus) {

		this.menus = menus;
	}

	@Override
	public String toString() {

		return this.name + " (ID: " + this.weekMenuTemplateID + ")";
	}

	@Override
	public Element toXML(Document doc) {

		return XMLGenerator.toXML(this, doc);
	}

	public Integer getStartYear() {

		return startYear;
	}

	public void setStartYear(Integer startYear) {

		this.startYear = startYear;
	}

	public Integer getEndWeek() {

		return endWeek;
	}

	public void setEndWeek(Integer endWeek) {

		this.endWeek = endWeek;
	}

	public Integer getEndYear() {

		return endYear;
	}

	public void setEndYear(Integer endYear) {

		this.endYear = endYear;
	}

	public boolean isEmpty() {
		for(WeekMenu m : menus){
			if(!m.isEmpty()){
				return false;
			}
		}

		return true;
	}

}
