package se.dosf.communitybase.modules.filearchive.beans;

import java.lang.reflect.Field;
import java.sql.Timestamp;
import java.util.List;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.beans.CommunityGroup;
import se.dosf.communitybase.beans.School;
import se.dosf.communitybase.interfaces.Accessible;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OneToMany;
import se.unlogic.standardutils.dao.annotations.SimplifiedRelation;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;

@Table(name="filearchive_sections")
@XMLElement
public class Section implements Elementable, Comparable<Section>, Accessible {

	public static final Field FILE_RELATION = ReflectionUtils.getField(Section.class, "files");
	public static final Field GROUP_RELATION = ReflectionUtils.getField(Section.class, "groups");
	public static final Field SCHOOL_RELATION = ReflectionUtils.getField(Section.class, "schools");
	
	@Key
	@DAOManaged(columnName="sectionID", autoGenerated=true)
	@XMLElement
	private Integer sectionID;
		
	@DAOManaged
	@WebPopulate(maxLength=65, required=true)
	@XMLElement(cdata=true)
	private String name;
	
	@DAOManaged
	@OneToMany(autoAdd=false,autoGet=false,autoUpdate=false)
	@XMLElement
	private List<File> files;
	
	@DAOManaged
	@OneToMany(autoGet=true, autoAdd=true, autoUpdate=true)
	@SimplifiedRelation(table="filearchive_sectiongroups",remoteKeyColumnName="sectionID",remoteValueColumnName="groupID")
	@XMLElement
	private List<CommunityGroup> groups;
	
	@DAOManaged
	@OneToMany(autoGet=true, autoAdd=true, autoUpdate=true)
	@SimplifiedRelation(table="filearchive_sectionschools",remoteKeyColumnName="sectionID",remoteValueColumnName="schoolID")
	@XMLElement
	private List<School> schools;
	
	@DAOManaged
	@XMLElement
	private boolean global;

	private Timestamp posted;

	public void setSectionID(Integer sectionID) {

		this.sectionID = sectionID;
	}

	public Integer getSectionID() {

		return sectionID;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getName() {

		return name;
	}

	@Override
	public String toString() {

		return StringUtils.substring(this.name, 30, "...") + " (ID: " + this.sectionID + ")";
	}

	@Override
	public Element toXML(Document doc) {
		
		return XMLGenerator.toXML(this, doc);
	}
	
	public List<File> getFiles() {

		return files;
	}

	public void setFiles(List<File> files) {

		this.files = files;
	}

	@Override
	public int compareTo(Section o) {

		return this.getName().compareTo(o.getName());
	}

	@Override
	public void setGroups(List<CommunityGroup> groups) {
		this.groups = groups;
	}

	@Override
	public List<CommunityGroup> getGroups() {
		return this.groups;
	}

	@Override
	public void setSchools(List<School> schools) {
		this.schools = schools;		
	}

	@Override
	public List<School> getSchools() {
		return this.schools;
	}

	@Override
	public void setGlobal(boolean global) {
		this.global = global;
	}

	@Override
	public boolean isGlobal() {
		return this.global;
	}

	public Timestamp getPosted() {

		return posted;
	}

	public void setPosted(Timestamp posted) {

		this.posted = posted;
	}
	
}