package se.dosf.communitybase.modules.pictureGallery.beans;

import java.sql.Timestamp;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.beans.CommunityUser;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToOne;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.enums.Order;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;

@Table(name="picturegallery_comments")
@XMLElement
public class Comment implements Elementable {

	@Key
	@DAOManaged(columnName="commentID", autoGenerated=true)
	@XMLElement
	private Integer commentID;
	
	@DAOManaged(columnName="pictureID")
	@ManyToOne(remoteKeyField="pictureID",autoAdd=false,autoGet=true,autoUpdate=false)
	@XMLElement
	private Picture picture;
	
	@DAOManaged
	@XMLElement(cdata=true)
	@WebPopulate(maxLength=65535, required=true)
	private String comment;
	
	@DAOManaged
	@OrderBy(order=Order.DESC,priority=1)
	@XMLElement
	private Timestamp posted = new Timestamp(System.currentTimeMillis());
	
	@DAOManaged
	@XMLElement(childName="poster")
	private CommunityUser poster;

	public Comment() {
		super();
	}

	public Integer getCommentID() {
		return commentID;
	}

	public void setCommentID(Integer commentID) {
		this.commentID = commentID;
	}

	public Picture getPicture() {
		return picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public CommunityUser getPoster() {
		return poster;
	}

	public void setPoster(CommunityUser poster) {
		this.poster = poster;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	
	public Timestamp getPosted() {
		return posted;
	}

	public void setPosted(Timestamp posted) {
		this.posted = posted;
	}

	@Override
	public String toString() {
		return StringUtils.substring(this.comment, 30, "...") + " (ID: " + this.commentID + ")";
	}

	@Override
	public Element toXML(Document doc) {
		return XMLGenerator.toXML(this, doc);		
	}
}