package se.dosf.communitybase.modules.pictureGallery.migration;

import java.lang.reflect.Field;
import java.sql.Blob;
import java.sql.Timestamp;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.beans.CommunityUser;
import se.dosf.communitybase.modules.pictureGallery.enums.ImageSize;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.OrderBy;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.date.DateUtils;
import se.unlogic.standardutils.enums.Order;
import se.unlogic.standardutils.reflection.ReflectionUtils;
import se.unlogic.standardutils.time.TimeUtils;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;
import se.unlogic.standardutils.xml.XMLUtils;

@Table(name = "picturegallery_pictures")
@XMLElement
public class PictureLegacy implements Elementable {

//	public static final Field GALLERY_RELATION = ReflectionUtils.getField(PictureLegacy.class, "gallery");
//	public static final Field COMMENT_RELATION = ReflectionUtils.getField(PictureLegacy.class, "comments");

	// These are required in order to be able to easily exclude these columns when making select queries
	public static final Field SMALL_THUMB_FIELD = ReflectionUtils.getField(PictureLegacy.class, "small");
	public static final Field MEDIUM_THUMB_FIELD = ReflectionUtils.getField(PictureLegacy.class, "medium");
	public static final Field DATA_FIELD = ReflectionUtils.getField(PictureLegacy.class, "full");

	@Key
	@DAOManaged(columnName = "pictureID", autoGenerated = true)
	@XMLElement
	private Integer pictureID;

	@DAOManaged
	@OrderBy(order = Order.DESC, priority = 2)
	@XMLElement
	private Timestamp posted = new Timestamp(System.currentTimeMillis());

	@DAOManaged
	@XMLElement(childName="poster")
	private CommunityUser poster;

	@DAOManaged(columnName = "galleryID")
//	@ManyToOne(remoteKeyField = "galleryID", autoAdd = false, autoGet = true, autoUpdate = false)
	@XMLElement
	private Integer gallery;

	@DAOManaged
	@OrderBy(order = Order.ASC, priority = 1)
	@XMLElement(cdata = true)
	private String filename;

	@DAOManaged
	private Blob small;

	@DAOManaged
	private Blob medium;

	@DAOManaged
	private Blob full;

//	@DAOManaged
//	@OneToMany
//	@XMLElement
//	private List<Comment> comments;

	public Integer getPictureID() {

		return pictureID;
	}

	public void setPictureID(Integer PictureLegacyID) {

		this.pictureID = PictureLegacyID;
	}

//	public Gallery getGallery() {
//
//		return gallery;
//	}
//
//	public void setGallery(Gallery gallery) {
//
//		this.gallery = gallery;
//	}

	public String getFilename() {

		return filename;
	}

	public void setFilename(String filename) {

		this.filename = filename;
	}

	public Blob getSmall() {
		return small;
	}

	public void setSmall(Blob small) {
		this.small = small;
	}

	public Blob getMedium() {
		return medium;
	}

	public void setMedium(Blob medium) {
		this.medium = medium;
	}

	public Blob getFull() {
		return full;
	}

	public void setFull(Blob full) {
		this.full = full;
	}

	public CommunityUser getPoster() {
		return poster;
	}

	public void setPoster(CommunityUser poster) {
		this.poster = poster;
	}

	public Timestamp getPosted() {

		return posted;
	}

	public void setPosted(Timestamp posted) {

		this.posted = posted;
	}

//	public List<Comment> getComments() {
//
//		return comments;
//	}
//
//	public void setComments(List<Comment> comments) {
//
//		this.comments = comments;
//	}

	public Blob getBlobForSize(ImageSize size) {

		if (ImageSize.SMALL.equals(size)) {
			return small;

		} else if (ImageSize.MEDIUM.equals(size)) {
			return medium;

		} else {
			return full;
		}
	}

	@Override
	public String toString() {

		return this.filename + " (ID: " + pictureID + ")";
	}

	@Override
	public int hashCode() {

		final int prime = 31;
		int result = 1;
		result = prime * result + ((pictureID == null) ? 0 : pictureID.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {

		if(this == obj){
			return true;
		}
		if(obj == null){
			return false;
		}
		if(getClass() != obj.getClass()){
			return false;
		}
		PictureLegacy other = (PictureLegacy) obj;
		if (pictureID == null) {
			if (other.pictureID != null) {
				return false;
			}
		} else if (!pictureID.equals(other.pictureID)) {
			return false;
		}
		return true;
	}

	@Override
	public Element toXML(Document doc) {

		Element PictureLegacyElement = XMLGenerator.toXML(this, doc);
		PictureLegacyElement.appendChild(XMLUtils.createElement("postedDate", DateUtils.DATE_FORMATTER.format(this.posted), doc));
		PictureLegacyElement.appendChild(XMLUtils.createElement("postedTime", TimeUtils.TIME_FORMATTER.format(this.posted), doc));
		PictureLegacyElement.appendChild(XMLUtils.createCDATAElement("postedInMillis", String.valueOf(this.posted.getTime()), doc));
		return PictureLegacyElement;
	}
}
