package se.dosf.communitybase.modules.absence.beans;

import java.sql.Timestamp;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.beans.CommunityGroup;
import se.dosf.communitybase.beans.CommunityUser;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.date.DateUtils;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.time.TimeUtils;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;
import se.unlogic.standardutils.xml.XMLUtils;

@Table(name="absences")
@XMLElement
public class Absence implements Elementable {

	@Key
	@DAOManaged(autoGenerated=true)
	@XMLElement
	private Integer absenceID;
	
	@DAOManaged(columnName="groupID")
	@XMLElement
	private CommunityGroup group;
	
	@DAOManaged
	@WebPopulate(maxLength=255, required=true)
	@XMLElement(cdata=true)
	private String name;
	
	@DAOManaged
	@XMLElement(cdata=true)
	@WebPopulate(maxLength=65535)
	private String comment;
	
	@DAOManaged
	private Timestamp startTime;
	
	@DAOManaged
	private Timestamp endTime;
	
	@DAOManaged
	@XMLElement
	private Timestamp posted;
	
	@DAOManaged(columnName="posterID")
	@XMLElement(childName="poster")
	private CommunityUser poster;
	
	@DAOManaged
	@XMLElement
	private Timestamp updated;
	
	@DAOManaged(columnName="editorID")
	@XMLElement(childName="editor")
	private CommunityUser editor;
	
	@XMLElement
	private boolean closed;
	
	public Integer getAbsenceID() {
		return absenceID;
	}

	public void setAbsenceID(Integer absenceID) {
		this.absenceID = absenceID;
	}

	public CommunityGroup getGroup() {
		return group;
	}

	public void setGroup(CommunityGroup group) {
		this.group = group;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Timestamp getStartTime() {
		return startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	public Timestamp getEndTime() {
		return endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public Timestamp getPosted() {
		return posted;
	}

	public void setPosted(Timestamp posted) {
		this.posted = posted;
	}

	public CommunityUser getPoster() {
		return poster;
	}

	public void setPoster(CommunityUser poster) {
		this.poster = poster;
	}

	public Timestamp getUpdated() {
		return updated;
	}

	public void setUpdated(Timestamp updated) {
		this.updated = updated;
	}

	public CommunityUser getEditor() {
		return editor;
	}

	public void setEditor(CommunityUser editor) {
		this.editor = editor;
	}

	public void setClosed(boolean closed) {
		this.closed = closed;
	}

	public boolean isClosed() {
		return closed;
	}

	public Element toXML(Document doc) {
		
		Element absenceElement = XMLGenerator.toXML(this, doc);
		
		if(startTime != null && endTime != null) {
			
			XMLUtils.appendNewElement(doc, absenceElement, "startTime", TimeUtils.TIME_FORMATTER.format(startTime));
			XMLUtils.appendNewElement(doc, absenceElement, "endTime", TimeUtils.TIME_FORMATTER.format(endTime));
			XMLUtils.appendNewElement(doc, absenceElement, "startDate", DateUtils.DATE_FORMATTER.format(startTime));
			XMLUtils.appendNewElement(doc, absenceElement, "endDate", DateUtils.DATE_FORMATTER.format(endTime));
			XMLUtils.appendNewElement(doc, absenceElement, "daysBetween", DateUtils.daysBetween(startTime, endTime) + 1);
			
		}
		
		return absenceElement;
	}
	
	@Override
	public String toString() {
		
		return StringUtils.substring(name, 30, "...") + " (ID: " + absenceID + ")";
	}

}
