package se.dosf.communitybase.beans;

import java.util.List;

import se.dosf.communitybase.interfaces.Role;
import se.unlogic.hierarchy.core.interfaces.Prioritized;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "communitybase_roles")
@XMLElement(name = "Role")
public class SimpleRole extends GeneratedElementable implements Role, Prioritized {

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer roleID;

	@DAOManaged
	@WebPopulate(required = true, maxLength = 255)
	@XMLElement
	private String name;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean addContentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean updateOwnContentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean deleteOwnContentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean updateOtherContentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean deleteOtherContentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean addCommentAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean manageMembersAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean manageModulesAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean manageSectionAccessModeAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean manageArchivedAccess;

	@DAOManaged
	@WebPopulate
	@XMLElement
	private boolean deleteRoomAccess;

	@DAOManaged
	@XMLElement
	private Integer priority;

	@DAOManaged
	@ManyToMany(linkTable = "communitybase_section_type_roles")
	@XMLElement
	private List<SimpleSectionType> sectionTypes;

	@Override
	public Integer getRoleID() {

		return roleID;
	}

	public void setRoleID(Integer roleID) {

		this.roleID = roleID;
	}

	@Override
	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	@Override
	public boolean hasAddContentAccess() {

		return addContentAccess;
	}

	public void setAddContentAccess(boolean addContentAccess) {

		this.addContentAccess = addContentAccess;
	}

	@Override
	public boolean hasUpdateOwnContentAccess() {

		return updateOwnContentAccess;
	}

	public void setUpdateOwnContentAccess(boolean updateOwnContentAccess) {

		this.updateOwnContentAccess = updateOwnContentAccess;
	}

	@Override
	public boolean hasDeleteOwnContentAccess() {

		return deleteOwnContentAccess;
	}

	public void setDeleteOwnContentAccess(boolean deleteOwnContentAccess) {

		this.deleteOwnContentAccess = deleteOwnContentAccess;
	}

	@Override
	public boolean hasUpdateOtherContentAccess() {

		return updateOtherContentAccess;
	}

	public void setUpdateOtherContentAccess(boolean updateOtherContentAccess) {

		this.updateOtherContentAccess = updateOtherContentAccess;
	}

	@Override
	public boolean hasDeleteOtherContentAccess() {

		return deleteOtherContentAccess;
	}

	public void setDeleteOtherContentAccess(boolean deleteOtherContentAccess) {

		this.deleteOtherContentAccess = deleteOtherContentAccess;
	}

	@Override
	public boolean hasAddCommentAccess() {

		return addCommentAccess;
	}

	public void setAddCommentAccess(boolean addCommentAccess) {

		this.addCommentAccess = addCommentAccess;
	}

	@Override
	public boolean hasManageMembersAccess() {

		return manageMembersAccess;
	}

	public void setManageMembersAccess(boolean manageMembersAccess) {

		this.manageMembersAccess = manageMembersAccess;
	}

	@Override
	public boolean hasManageModulesAccess() {

		return manageModulesAccess;
	}

	public void setManageModulesAccess(boolean manageModulesAccess) {

		this.manageModulesAccess = manageModulesAccess;
	}

	@Override
	public boolean hasManageSectionAccessModeAccess() {

		return manageSectionAccessModeAccess;
	}

	public void setManageSectionAccessModeAccess(boolean manageSectionAccessModeAccess) {

		this.manageSectionAccessModeAccess = manageSectionAccessModeAccess;
	}

	@Override
	public List<SimpleSectionType> getSectionTypes() {

		return sectionTypes;
	}

	public void setSectionTypes(List<SimpleSectionType> sectionTypes) {

		this.sectionTypes = sectionTypes;
	}

	@Override
	public String toString() {

		return name + " (roleID: " + roleID + ")";
	}

	public void setManageArchivedAccess(boolean manageArchivedAccess) {

		this.manageArchivedAccess = manageArchivedAccess;
	}

	public void setDeleteRoomAccess(boolean deleteRoomAccess) {

		this.deleteRoomAccess = deleteRoomAccess;
	}

	@Override
	public boolean hasManageArchivedAccess() {

		return manageArchivedAccess;
	}

	@Override
	public boolean hasDeleteRoomAccess() {

		return deleteRoomAccess;
	}

	@Override
	public int getPriority() {

		return priority;
	}

	public void setPriority(int priority) {

		this.priority = priority;
	}
}
