package se.dosf.communitybase.modules.weekmenu.beans;

import java.sql.Timestamp;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import se.dosf.communitybase.beans.CommunityUser;
import se.dosf.communitybase.beans.School;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.Elementable;
import se.unlogic.standardutils.xml.XMLElement;
import se.unlogic.standardutils.xml.XMLGenerator;

@Table(name = "weekmenu_school_menus")
@XMLElement
public class SchoolMenu implements Elementable {

	@DAOManaged(autoGenerated = true)
	@Key
	@XMLElement
	private Integer schoolMenuID;

	@DAOManaged(columnName = "schoolID")
	@XMLElement
	private School school;

	@DAOManaged
	@XMLElement
	private Integer year;

	@DAOManaged
	@XMLElement
	private Integer week;

	@DAOManaged(columnName = "posterID", dontUpdateIfNull = true)
	@XMLElement(childName = "poster")
	private CommunityUser poster;

	@DAOManaged
	@XMLElement
	private Timestamp created;

	@DAOManaged
	@XMLElement
	private Timestamp lastEdit;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String monday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String tuesday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String wednesday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String thursday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String friday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String saturday;

	@DAOManaged
	@WebPopulate(maxLength = 255)
	@XMLElement
	private String sunday;

	public School getSchool() {

		return school;
	}

	public void setSchool(School school) {

		this.school = school;
	}

	public Integer getWeek() {

		return week;
	}

	public void setWeek(Integer week) {

		this.week = week;
	}

	public CommunityUser getPoster() {

		return poster;
	}

	public void setPoster(CommunityUser poster) {

		this.poster = poster;
	}

	public Timestamp getLastEdit() {

		return lastEdit;
	}

	public void setLastEdit(Timestamp lastEdit) {

		this.lastEdit = lastEdit;
	}

	public String getMonday() {

		return monday;
	}

	public void setMonday(String mondayTitle) {

		this.monday = mondayTitle;
	}

	public String getTuesday() {

		return tuesday;
	}

	public void setTuesday(String tuesdayTitle) {

		this.tuesday = tuesdayTitle;
	}

	public String getWednesday() {

		return wednesday;
	}

	public void setWednesday(String wednesdayTitle) {

		this.wednesday = wednesdayTitle;
	}

	public String getThursday() {

		return thursday;
	}

	public void setThursday(String thursdayTitle) {

		this.thursday = thursdayTitle;
	}

	public String getFriday() {

		return friday;
	}

	public void setFriday(String fridayTitle) {

		this.friday = fridayTitle;
	}

	public String getSaturday() {

		return saturday;
	}

	public void setSaturday(String saturdayTitle) {

		this.saturday = saturdayTitle;
	}

	public String getSunday() {

		return sunday;
	}

	public void setSunday(String sundayTitle) {

		this.sunday = sundayTitle;
	}

	public Integer getYear() {

		return year;
	}

	public void setYear(Integer year) {

		this.year = year;
	}

	public Timestamp getCreated() {

		return created;
	}

	public void setCreated(Timestamp created) {

		this.created = created;
	}

	public Integer getSchoolMenuID() {

		return schoolMenuID;
	}

	public void setSchoolMenuID(Integer schoolMenuID) {

		this.schoolMenuID = schoolMenuID;
	}

	public boolean isEmpty() {

		return monday == null && tuesday == null && wednesday == null && friday == null && saturday == null && wednesday == null;
	}

	@Override
	public String toString() {

		return year + " V." + this.week + "(ID: " + schoolMenuID + ")";
	}

	@Override
	public Element toXML(Document doc) {

		return XMLGenerator.toXML(this, doc);
	}

}
